In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, RidgeCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LassoCV, ElasticNetCV
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import kurtosis

In [2]:
wine = pd.read_csv('Wine_New.csv')
wine.head()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,14.597442,0.27,0.722678,20.7,0.255607,137.728720,53.053366,1.0010,3.128677,0.471783,11.309539,6.0
1,8.288791,0.30,1.749025,1.6,0.128959,86.111551,64.933772,0.9940,3.691148,0.923397,8.126983,5.0
2,3.089898,0.28,0.837108,6.9,0.306241,8.266643,26.102900,0.9951,3.549499,1.016564,11.247490,5.0
3,13.931712,0.23,0.241370,8.5,0.266436,212.246505,16.764493,0.9956,2.867154,0.507882,11.104247,6.0
4,14.271228,0.23,0.717399,8.5,0.320200,109.031626,424.269899,0.9956,2.865725,0.883249,8.062316,6.0

In [3]:
wine_poor =wine[(wine['quality']<6)]
wine_poor.head()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,8.288791,0.30,1.749025,1.6,0.128959,86.111551,64.933772,0.9940,3.691148,0.923397,8.126983,5.0
2,3.089898,0.28,0.837108,6.9,0.306241,8.266643,26.102900,0.9951,3.549499,1.016564,11.247490,5.0
7,4.007259,0.27,0.114301,20.7,0.311429,47.942185,347.504463,1.0010,3.069059,1.001918,11.736427,5.0
8,12.197771,0.30,1.353443,1.6,0.131701,133.452682,344.047374,0.9940,2.962240,0.245577,11.865377,5.0
9,5.841717,0.22,0.192240,1.5,0.257865,182.925867,230.706425,0.9938,3.342903,0.851317,8.137473,5.0

In [4]:
wine_poor.count()

fixed acidity           1018
volatile acidity        1018
critric acid            1018
residual sugar          1018
chlorides               1018
free sulfur dioxide     1018
total sulfur dioxide    1018
density                 1018
pH                      1018
sulphates               1018
alcohol                 1018
quality                 1018
dtype: int64

In [5]:
wine_poor['quality'].describe()

count    1018.000000
mean        4.909627
std         0.303512
min         2.000000
25%         5.000000
50%         5.000000
75%         5.000000
max         5.000000
Name: quality, dtype: float64

In [6]:
density=wine['density']
residual_sugar=wine['residual sugar']
volatile_acidity=wine['volatile acidity']
quality=wine['quality']

In [7]:
wine1=wine[['quality','density','residual sugar','volatile acidity']]
wine1.head()

   quality  density  residual sugar  volatile acidity
0      6.0   1.0010            20.7              0.27
1      5.0   0.9940             1.6              0.30
2      5.0   0.9951             6.9              0.28
3      6.0   0.9956             8.5              0.23
4      6.0   0.9956             8.5              0.23

In [8]:
wine1.corr()

                   quality   density  residual sugar  volatile acidity
quality           1.000000 -0.225504       -0.023050         -0.213460
density          -0.225504  1.000000        0.839781          0.062720
residual sugar   -0.023050  0.839781        1.000000          0.092867
volatile acidity -0.213460  0.062720        0.092867          1.000000

In [9]:
residual_sugar.head()

0    20.7
1     1.6
2     6.9
3     8.5
4     8.5
Name: residual sugar, dtype: float64

In [10]:
volatile_acidity.head()

0    0.27
1    0.30
2    0.28
3    0.23
4    0.23
Name: volatile acidity, dtype: float64

In [11]:
wine.corr()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.000507,-0.005350,-0.000353,0.008160,0.028897,-0.022439,0.001055,-0.002756,-0.008172,0.013041,0.469078
volatile acidity,-0.000507,1.000000,-0.009634,0.092867,0.003054,0.012155,0.022878,0.062720,-0.012604,0.003202,-0.002991,-0.213460
critric acid,-0.005350,-0.009634,1.000000,-0.013108,0.013268,0.018540,-0.003182,-0.016051,0.041180,-0.002692,-0.027137,0.003186
residual sugar,-0.000353,0.092867,-0.013108,1.000000,-0.003475,-0.028105,-0.003072,0.839781,0.009022,0.011107,-0.003176,-0.023050
chlorides,0.008160,0.003054,0.013268,-0.003475,1.000000,0.014025,-0.006618,-0.020391,-0.008223,0.010086,0.014409,-0.053384
free sulfur dioxide,0.028897,0.012155,0.018540,-0.028105,0.014025,1.000000,0.014553,-0.022882,0.015549,-0.011700,-0.015964,0.462151
total sulfur dioxide,-0.022439,0.022878,-0.003182,-0.003072,-0.006618,0.014553,1.000000,-0.004695,-0.005970,0.006921,0.002192,-0.061752
density,0.001055,0.062720,-0.016051,0.839781,-0.020391,-0.022882,-0.004695,1.000000,-0.004419,0.021988,0.002265,-0.225504
pH,-0.002756,-0.012604,0.041180,0.009022,-0.008223,0.015549,-0.005970,-0.004419,1.000000,0.008990,-0.016355,0.355839
sulphates,-0.008172,0.003202,-0.002692,0.011107,0.010086,-0.011700,0.006921,0.021988,0.008990,1.000000,0.002504,0.176389
alcohol,0.013041,-0.002991,-0.027137,-0.003176,0.014409,-0.015964,0.002192,0.002265,-0.016355,0.002504,1.000000,0.290262
quality,0.469078,-0.213460,0.003186,-0.023050,-0.053384,0.462151,-0.061752,-0.225504,0.355839,0.176389,0.290262,1.000000

In [12]:
density.corr(residual_sugar,)

0.8397811198409381

In [13]:
density.corr(volatile_acidity,)

0.06271995565002475

In [14]:
volatile_acidity.corr(residual_sugar)

0.09286723742146968

In [15]:
X = wine.iloc[:, :-1] # x features
y = wine.iloc[:, -1] # y responses value

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)

In [17]:
# with intercept
lr_obj = LinearRegression()
lr_obj.fit(X_train, y_train)
preds_ols = lr_obj.predict(X_test)
print("OLS: {0}".format(mean_squared_error(y_test, preds_ols)/2))

OLS: 0.04408878343551022

In [18]:
print(lr_obj.intercept_)
print(lr_obj.coef_)

191.72795102466608
[ 1.06178984e-01 -1.81652548e+00 -1.13278471e-02  9.60281440e-02
 -6.92019660e-01  4.45600635e-03 -3.61260704e-04 -1.93013454e+02
  8.26661990e-01  6.23347316e-01  1.39425673e-01]

In [19]:
#without intercept
lrr_obj = LinearRegression(fit_intercept=False, normalize=False, copy_X=True, n_jobs=None)
lrr_obj.fit(X_train, y_train)
preds_ols = lrr_obj.predict(X_test)
print("OLS: {0}".format(mean_squared_error(y_test, preds_ols)/2))

OLS: 0.0938192131663866

In [20]:
print(lrr_obj.intercept_)
# For other beta
print(lrr_obj.coef_)

0.0
[ 1.07009433e-01 -1.74336964e+00 -3.94527416e-03  1.50591828e-04
 -5.42979277e-01  4.47821549e-03 -3.16203898e-04  2.88867109e-01
  8.63977548e-01  5.92103646e-01  1.37807260e-01]

In [21]:
#q3

In [22]:
y_train.mean()

6.0071875

In [23]:
y_train.describe()

count    3200.000000
mean        6.007187
std         0.812307
min         2.000000
25%         5.000000
50%         6.000000
75%         7.000000
max         8.000000
Name: quality, dtype: float64

In [24]:
ycenter_train=y_train-y_train.mean()

In [25]:
x_new1=X_train['fixed acidity']-X_train['fixed acidity'].mean()

In [26]:
x_new2=X_train['volatile acidity']-X_train['volatile acidity'].mean()

In [27]:
x_new3=X_train['critric acid']-X_train['critric acid'].mean()

In [28]:
x_new4=X_train['residual sugar']-X_train['residual sugar'].mean()

In [29]:
x_new5=X_train['chlorides']-X_train['chlorides'].mean()

In [30]:
x_new6=X_train['free sulfur dioxide']-X_train['free sulfur dioxide'].mean()

In [31]:
x_new7=X_train['total sulfur dioxide']-X_train['total sulfur dioxide'].mean()

In [32]:
x_new8=X_train['density']-X_train['density'].mean()

In [33]:
x_new9=X_train['pH']-X_train['pH'].mean()

In [34]:
x_new10=X_train['sulphates']-X_train['sulphates'].mean()

In [35]:
x_new11=X_train['alcohol']-X_train['alcohol'].mean()

In [36]:
xcenter_train=pd.DataFrame([x_new1,x_new2,x_new3,x_new4,x_new5,x_new6,x_new7,x_new8,x_new9,x_new10,x_new11]).T

In [37]:
x_testnew1=X_test['fixed acidity']-X_test['fixed acidity'].mean()

In [38]:
x_testnew2=X_test['volatile acidity']-X_test['volatile acidity'].mean()

In [39]:
x_testnew3=X_test['critric acid']-X_test['critric acid'].mean()

In [40]:
x_testnew4=X_test['residual sugar']-X_test['residual sugar'].mean()

In [41]:
x_testnew5=X_test['chlorides']-X_test['chlorides'].mean()

In [42]:
x_testnew6=X_test['free sulfur dioxide']-X_test['free sulfur dioxide'].mean()

In [43]:
x_testnew7=X_test['total sulfur dioxide']-X_test['total sulfur dioxide'].mean()

In [44]:
x_testnew8=X_test['density']-X_test['density'].mean()

In [45]:
x_testnew9=X_test['pH']-X_test['pH'].mean()

In [46]:
x_testnew10=X_test['sulphates']-X_test['sulphates'].mean()

In [47]:
x_testnew11=X_test['alcohol']-X_test['alcohol'].mean()

In [48]:
xcenter_test=pd.DataFrame([x_testnew1,x_testnew2,x_testnew3,x_testnew4,x_testnew5,
                          x_testnew6,x_testnew7,x_testnew8,x_testnew9,x_testnew10,x_testnew11]).T

In [49]:
y_testnew=y_test-y_test.mean()

In [50]:
lrr3_obj = LinearRegression()
lrr3_obj.fit(xcenter_train, ycenter_train)
preds_ols = lrr3_obj.predict(xcenter_test)
print("OLS: {0}".format(mean_squared_error(y_testnew, preds_ols)/2))

OLS: 0.04408760013659672

In [51]:
#with intercept
print(lrr3_obj.intercept_)
# For other beta
print(lrr3_obj.coef_)

8.701195627973102e-13
[ 1.06178984e-01 -1.81652548e+00 -1.13278471e-02  9.60281440e-02
 -6.92019660e-01  4.45600635e-03 -3.61260704e-04 -1.93013454e+02
  8.26661990e-01  6.23347316e-01  1.39425673e-01]

In [52]:
# #without intercept(没用)
# lrr32_obj = LinearRegression(fit_intercept=False, normalize=False, copy_X=True, n_jobs=None)
# lrr32_obj.fit(xcenter_train, ycenter_train)
# preds_ols = lrr32_obj.predict(xcenter_test)
# print("OLS: {0}".format(mean_squared_error(y_testnew, preds_ols)/2))

In [53]:
#with intercept
# print(lrr32_obj.intercept_)
# # For other beta
# print(lrr32_obj.coef_)

In [54]:
#Q4(1)

In [55]:
wine_poor =wine[(wine['quality']<6)].sample(n=200, random_state=0)
wine_poor.head()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1683,3.126106,0.25,0.467807,14.4,0.100180,47.163696,56.945707,0.99860,3.068051,1.021860,13.246068,5.0
2170,3.894873,0.19,0.412399,12.8,0.077457,29.217110,278.019507,0.99860,3.449873,0.615338,13.203304,5.0
875,3.379725,0.21,1.504676,2.2,0.330457,8.185828,219.387711,0.99300,3.788070,0.936848,8.310725,5.0
2643,3.103476,0.33,0.034377,5.2,0.241864,30.300393,328.126821,0.99527,2.982601,0.439957,13.577000,4.0
68,12.808128,0.23,0.706059,2.1,0.291294,43.704137,93.034501,0.99260,2.848031,0.259820,11.667792,5.0

In [56]:
wine_good=wine[(wine['quality']>=6)].sample(n=200,random_state=0)
wine_good.head()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
440,12.596189,0.22,1.649097,1.6,0.280095,97.216994,225.231025,0.99130,3.601343,0.449338,14.018333,7.0
3252,10.738063,0.26,0.533391,5.5,0.154494,83.497748,92.159496,0.99082,2.962823,0.674119,10.051296,6.0
3488,13.355930,0.20,0.351990,1.4,0.004891,127.989063,355.969589,0.99088,3.564018,0.594325,10.393825,7.0
1246,13.128423,0.20,1.523367,5.2,0.035838,150.559414,260.664700,0.99530,3.398588,0.558451,9.576683,6.0
1802,8.352261,0.23,0.434546,15.4,0.047682,42.040804,68.106984,0.99840,3.580832,0.794874,12.416746,6.0

In [57]:
wine_new=pd.concat([wine_good, wine_poor])
wine_new.head()

,fixed acidity,volatile acidity,critric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
440,12.596189,0.22,1.649097,1.6,0.280095,97.216994,225.231025,0.99130,3.601343,0.449338,14.018333,7.0
3252,10.738063,0.26,0.533391,5.5,0.154494,83.497748,92.159496,0.99082,2.962823,0.674119,10.051296,6.0
3488,13.355930,0.20,0.351990,1.4,0.004891,127.989063,355.969589,0.99088,3.564018,0.594325,10.393825,7.0
1246,13.128423,0.20,1.523367,5.2,0.035838,150.559414,260.664700,0.99530,3.398588,0.558451,9.576683,6.0
1802,8.352261,0.23,0.434546,15.4,0.047682,42.040804,68.106984,0.99840,3.580832,0.794874,12.416746,6.0

In [58]:
#Q4(2)

In [59]:
x = wine_new.iloc[:, :-1] # x features
y = wine_new.iloc[:, -1] 
X_latrain, X_latest, y_latrain, y_latest = train_test_split(x,y,test_size=0.2, random_state=0,)

In [60]:
x_nnew1=X_latrain['fixed acidity']-X_latrain['fixed acidity'].mean();
x_nnew2=X_latrain['volatile acidity']-X_latrain['volatile acidity'].mean();
x_nnew3=X_latrain['critric acid']-X_latrain['critric acid'].mean();
x_nnew4=X_latrain['residual sugar']-X_latrain['residual sugar'].mean();
x_nnew5=X_latrain['chlorides']-X_latrain['chlorides'].mean();
x_nnew6=X_latrain['free sulfur dioxide']-X_latrain['free sulfur dioxide'].mean();
x_nnew7=X_latrain['total sulfur dioxide']-X_latrain['total sulfur dioxide'].mean();
x_nnew8=X_latrain['density']-X_latrain['density'].mean();
x_nnew9=X_latrain['pH']-X_latrain['pH'].mean();
x_nnew10=X_latrain['sulphates']-X_latrain['sulphates'].mean();
x_nnew11=X_latrain['alcohol']-X_latrain['alcohol'].mean();
X_latrain=pd.DataFrame([x_nnew1,x_nnew2,x_nnew3,x_nnew4,x_nnew5,x_nnew6,x_nnew7,x_nnew8,x_nnew9,x_nnew10,x_nnew11]).T

In [61]:
x_testnnew1=X_latest['fixed acidity']-X_test['fixed acidity'].mean();
x_testnnew2=X_latest['volatile acidity']-X_test['volatile acidity'].mean();
x_testnnew3=X_latest['critric acid']-X_test['critric acid'].mean();
x_testnnew4=X_latest['residual sugar']-X_test['residual sugar'].mean();  
x_testnnew5=X_latest['chlorides']-X_test['chlorides'].mean();
x_testnnew6=X_latest['free sulfur dioxide']-X_test['free sulfur dioxide'].mean();
x_testnnew7=X_latest['total sulfur dioxide']-X_test['total sulfur dioxide'].mean();
x_testnnew8=X_latest['density']-X_test['density'].mean();
x_testnnew9=X_latest['pH']-X_test['pH'].mean();
x_testnnew10=X_latest['sulphates']-X_test['sulphates'].mean();
x_testnnew11=X_latest['alcohol']-X_test['alcohol'].mean();
X_latest=pd.DataFrame([x_testnnew1,x_testnnew2,x_testnnew3,x_testnnew4,x_testnnew5,
                          x_testnnew6,x_testnnew7,x_testnnew8,x_testnnew9,x_testnnew10,x_testnnew11]).T

In [62]:
y_latrain=y_latrain-y_latrain.mean()

In [63]:
y_latest=y_latest-y_latest.mean()

In [64]:
#alpha lamda /2n

In [65]:
alpha_range=10.**np.arange(-2,3)
lascv = LassoCV(normalize=True,alphas=alpha_range)
lascv.fit(X_latrain, y_latrain)
preds_lassocv = lascv.predict(X_latest)
print("LASSO: {0}".format(mean_squared_error(y_latest, preds_lassocv)/2))
print("LASSO Lambda: {0}".format(lascv.alpha_))

LASSO: 0.19752397827799578
LASSO Lambda: 0.01

/Users/apple/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

In [66]:
lascv = LassoCV()
lascv.fit(X_latrain, y_latrain)
preds_lassocv = lascv.predict(X_latest)
print("LASSO: {0}".format(mean_squared_error(y_latest, preds_lassocv)/2))
print("LASSO Lambda: {0}".format(lascv.alpha_))

LASSO: 0.14554109225552975
LASSO Lambda: 0.03781501842857406

/Users/apple/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)

In [67]:
#taskB Q1

In [68]:
loans = pd.read_excel('Loans_Data_New.xlsx')
loans.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,...,title,addr_state,dti,earliest_cr_line,inq_last_6mths,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,debt_settlement_flag
0,12000,12000,12000.00000,36 months,0.1242,400.99,B,B4,5 years,RENT,...,payoff,NJ,22.49,2003-09-01,0,14435.349990,14435.35,12000.00,2435.35,N
1,8000,8000,8000.00000,60 months,0.1521,191.21,D,D2,5 years,RENT,...,Ratha's loan,PA,21.43,1998-12-01,0,9061.140000,9061.14,5704.48,3356.66,Y
2,7000,7000,7000.00000,36 months,0.1065,228.02,B,B2,< 1 year,RENT,...,Loan 12142011,CA,7.38,2004-04-01,0,8208.410003,8208.41,7000.00,1208.41,N
3,21600,21600,20498.26578,60 months,0.1942,565.32,E,E3,8 years,MORTGAGE,...,5 Years to Financial Freedom,GA,16.74,1990-12-01,0,27586.781410,24859.66,21600.00,5986.78,N
4,33425,20675,19010.82122,60 months,0.1349,475.63,C,C1,2 years,MORTGAGE,...,Debt Consolidation Loan,NY,25.71,1978-07-01,3,19893.950000,16765.31,13371.26,6512.03,Y

In [69]:
LCD=pd.read_excel('LCDataDictionary.xlsx')
LCD.head()

            LoanStatNew                                        Description
0        acc_now_delinq  The number of accounts on which the borrower i...
1  acc_open_past_24mths         Number of trades opened in past 24 months.
2            addr_state  The state provided by the borrower in the loan...
3              all_util              Balance to credit limit on all trades
4            annual_inc  The self-reported annual income provided by th...

In [70]:
loans.isnull().sum()

loan_amnt                0
funded_amnt              0
funded_amnt_inv          0
term                     0
int_rate                 0
installment              0
grade                    0
sub_grade                0
emp_length              14
home_ownership           0
annual_inc               0
verification_status      0
loan_status              0
pymnt_plan               0
purpose                  0
title                    0
addr_state               0
dti                      0
earliest_cr_line         0
inq_last_6mths           0
total_pymnt              0
total_pymnt_inv          0
total_rec_prncp          0
total_rec_int            0
debt_settlement_flag     0
dtype: int64

In [71]:
dummies_loans = pd.get_dummies(loans,drop_first = True)
dummies_loans.head()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,earliest_cr_line,inq_last_6mths,total_pymnt,...,addr_state_SD,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,debt_settlement_flag_Y
0,12000,12000,12000.00000,0.1242,400.99,50700.0,22.49,2003-09-01,0,14435.349990,...,0,0,0,0,0,0,0,0,0,0
1,8000,8000,8000.00000,0.1521,191.21,29000.0,21.43,1998-12-01,0,9061.140000,...,0,0,0,0,0,0,0,0,0,1
2,7000,7000,7000.00000,0.1065,228.02,40000.0,7.38,2004-04-01,0,8208.410003,...,0,0,0,0,0,0,0,0,0,0
3,21600,21600,20498.26578,0.1942,565.32,60000.0,16.74,1990-12-01,0,27586.781410,...,0,0,0,0,0,0,0,0,0,0
4,33425,20675,19010.82122,0.1349,475.63,75000.0,25.71,1978-07-01,3,19893.950000,...,0,0,0,0,0,0,0,0,0,1

In [72]:
dummies_loans.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,inq_last_6mths,total_pymnt,total_pymnt_inv,...,addr_state_SD,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,debt_settlement_flag_Y
count,565.000000,565.000000,565.000000,565.000000,565.000000,565.000000,565.000000,565.000000,565.000000,565.000000,...,565.00000,565.000000,565.00000,565.000000,565.00000,565.000000,565.000000,565.000000,565.00000,565.000000
mean,13039.469027,12623.362832,12263.498532,0.132404,372.314867,63990.414425,14.521009,0.991150,13233.126934,12839.506124,...,0.00177,0.072566,0.00177,0.035398,0.00177,0.024779,0.014159,0.007080,0.00177,0.283186
std,7846.395883,7335.373208,7164.897656,0.039057,208.949707,37034.292456,6.408200,1.341479,8743.003971,8539.098131,...,0.04207,0.259653,0.04207,0.184948,0.04207,0.155588,0.118252,0.083917,0.04207,0.450945
min,1000.000000,1000.000000,0.000000,0.057900,35.310000,12000.000000,0.370000,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,7200.000000,7200.000000,7000.000000,0.106500,215.690000,40000.000000,9.860000,0.000000,6858.700001,6461.140000,...,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,11100.000000,11000.000000,10500.000000,0.126900,337.750000,55000.000000,14.650000,1.000000,11264.480000,11123.650000,...,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000
75%,18000.000000,17000.000000,16060.110690,0.162900,474.190000,78000.000000,19.740000,2.000000,17402.239990,16917.780000,...,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,1.000000
max,35000.000000,35000.000000,35000.000000,0.239100,1269.730000,290000.000000,29.850000,14.000000,48587.490000,48587.490000,...,1.00000,1.000000,1.00000,1.000000,1.00000,1.000000,1.000000,1.000000,1.00000,1.000000

In [73]:
dummies_loans.corr()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,inq_last_6mths,total_pymnt,total_pymnt_inv,...,addr_state_SD,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,debt_settlement_flag_Y
loan_amnt,1.000000,0.969952,0.940433,0.365814,0.905620,0.478097,0.043927,0.018862,0.844806,0.813988,...,-0.021697,0.093604,-0.037811,-0.000048,-0.016326,-0.011296,-0.007626,-0.019275,0.064243,0.219288
funded_amnt,0.969952,1.000000,0.971108,0.334877,0.950298,0.447400,0.046127,0.006458,0.865591,0.835748,...,-0.020818,0.084007,-0.038054,-0.014301,-0.015072,-0.003033,-0.001353,-0.015823,0.071109,0.221004
funded_amnt_inv,0.940433,0.971108,1.000000,0.314638,0.919519,0.405626,0.043343,-0.028715,0.856258,0.869783,...,-0.019196,0.089012,-0.036843,-0.018263,-0.013314,0.004710,0.004587,-0.011955,0.074771,0.167402
int_rate,0.365814,0.334877,0.314638,1.000000,0.274585,0.166713,0.159055,0.189734,0.335730,0.314901,...,-0.027952,0.039276,-0.016514,0.078576,-0.035937,0.064029,0.046133,-0.035171,0.062474,0.229406
installment,0.905620,0.950298,0.919519,0.274585,1.000000,0.431917,0.038713,0.023762,0.826838,0.800227,...,-0.015965,0.071730,-0.035066,-0.030311,-0.010098,-0.005801,0.008258,0.002047,0.055793,0.144573
annual_inc,0.478097,0.447400,0.405626,0.166713,0.431917,1.000000,-0.178688,0.005153,0.380912,0.349618,...,0.011391,0.010673,0.022771,-0.025891,-0.038681,-0.072332,-0.018495,-0.013614,0.012529,0.161117
dti,0.043927,0.046127,0.043343,0.159055,0.038713,-0.178688,1.000000,0.088075,0.044271,0.041751,...,-0.037034,0.022205,0.025774,0.007929,-0.021578,0.005470,0.054802,0.020561,0.033600,0.014596
inq_last_6mths,0.018862,0.006458,-0.028715,0.189734,0.023762,0.005153,0.088075,1.000000,-0.030694,-0.055220,...,-0.031139,-0.028695,-0.031139,0.101314,0.000278,-0.049917,0.090208,0.095059,0.031695,0.174147
total_pymnt,0.844806,0.865591,0.856258,0.335730,0.826838,0.380912,0.044271,-0.030694,1.000000,0.981246,...,-0.012916,0.083680,-0.029241,0.016867,-0.008897,0.001228,-0.004268,-0.022740,0.122908,0.087301
total_pymnt_inv,0.813988,0.835748,0.869783,0.314901,0.800227,0.349618,0.041751,-0.055220,0.981246,1.000000,...,-0.011281,0.087066,-0.027996,0.007817,-0.007167,0.008419,0.001139,-0.019388,0.127594,0.043544
total_rec_prncp,0.688293,0.707433,0.722921,0.087595,0.726898,0.295723,0.003814,-0.090206,0.888762,0.892991,...,-0.003338,0.057572,-0.022578,-0.019535,0.003075,0.005344,-0.000668,-0.026505,0.099276,-0.172162
total_rec_int,0.710224,0.717698,0.705858,0.552816,0.601891,0.293237,0.084944,-0.002629,0.822589,0.799488,...,-0.018753,0.081162,-0.024444,0.065936,-0.021109,0.018768,-0.023198,-0.021239,0.153756,0.245000
term_ 60 months,0.418821,0.372262,0.366203,0.522401,0.115501,0.167809,0.065567,0.035491,0.330542,0.313334,...,-0.029735,0.048614,-0.029735,0.067998,-0.029735,0.032418,-0.021045,-0.059629,0.059628,0.323152
grade_B,-0.082622,-0.067869,-0.042168,-0.306067,-0.036942,-0.015976,-0.028744,-0.124446,-0.077036,-0.056034,...,0.059867,0.035233,0.059867,-0.032964,0.059867,0.033061,-0.052458,-0.059391,-0.029617,-0.191640
grade_C,-0.065988,-0.050741,-0.062463,0.134161,-0.033615,-0.108435,0.023790,0.143085,-0.045262,-0.056113,...,-0.021635,-0.009447,-0.021635,-0.004171,-0.021635,-0.025878,0.048986,0.008548,-0.021635,-0.004020
grade_D,0.053874,0.030040,0.029915,0.370053,0.008406,0.016891,0.100833,0.066154,0.018047,0.021857,...,-0.017473,-0.019715,-0.017473,0.028733,-0.017473,-0.001822,0.034902,-0.035040,-0.017473,0.127564
grade_E,0.259928,0.228896,0.208088,0.410088,0.152958,0.144876,0.074737,0.049806,0.247717,0.226962,...,-0.012684,-0.010144,-0.012684,0.011663,-0.012684,0.034442,0.018146,-0.025435,0.139790,0.166292
grade_F,0.195545,0.203657,0.189613,0.385540,0.199437,0.152509,-0.013730,0.095989,0.188037,0.178064,...,-0.009248,0.068812,-0.009248,0.003641,-0.009248,0.019332,-0.026321,0.082207,-0.009248,0.180688
grade_G,0.112251,0.090082,0.039418,0.218359,0.080375,0.081225,-0.022455,0.052216,0.093987,0.044686,...,-0.004362,0.037580,-0.004362,0.167042,-0.004362,-0.016514,-0.012416,-0.008748,-0.004362,0.126506
sub_grade_A2,-0.091096,-0.087750,-0.083126,-0.298160,-0.087072,0.020225,0.039386,-0.054598,-0.085951,-0.081493,...,-0.007188,-0.047753,-0.007188,0.025038,-0.007188,-0.027212,-0.020459,-0.014415,-0.007188,-0.012574
sub_grade_A3,-0.097385,-0.095119,-0.089409,-0.235797,-0.088424,-0.105222,0.003478,-0.015937,-0.090392,-0.085233,...,-0.006712,-0.044588,-0.006712,-0.030535,-0.006712,-0.025408,-0.019103,-0.013460,-0.006712,-0.049647
sub_grade_A4,-0.085682,-0.078445,-0.068702,-0.324020,-0.064905,-0.046288,-0.063940,-0.070277,-0.071384,-0.062435,...,-0.009794,-0.034146,-0.009794,-0.044559,-0.009794,-0.037077,0.040012,0.076024,-0.009794,-0.057188
sub_grade_A5,-0.021116,-0.010892,-0.001025,-0.242829,0.013959,-0.042648,-0.062059,-0.092194,-0.020916,-0.012150,...,-0.008674,0.011427,-0.008674,-0.039462,-0.008674,0.024780,-0.024688,-0.017395,-0.008674,-0.049962
sub_grade_B1,-0.021525,-0.009113,0.002613,-0.209666,0.017136,-0.040886,-0.046668,-0.026947,0.009950,0.021130,...,-0.010317,-0.009508,-0.010317,-0.046938,0.171850,-0.039057,-0.029365,-0.020690,-0.010317,-0.137013
sub_grade_B2,-0.026159,-0.023032,-0.013464,-0.145924,-0.000755,0.019023,-0.044366,-0.042668,-0.011953,-0.003180,...,0.191720,0.101374,-0.009248,-0.042074,-0.009248,-0.035009,-0.026321,-0.018546,-0.009248,-0.100548
sub_grade_B3,-0.089083,-0.085278,-0.079688,-0.123228,-0.073467,-0.034014,-0.018068,-0.131133,-0.085701,-0.082358,...,-0.012237,-0.030371,0.144895,0.015815,-0.012237,-0.003835,-0.034828,-0.024539,-0.012237,-0.080043
sub_grade_B4,0.023664,0.020071,0.032007,-0.074635,0.027390,0.094420,0.025403,-0.076926,-0.004162,0.004896,...,-0.012237,0.071466,-0.012237,-0.019927,-0.012237,0.038653,-0.034828,-0.024539,-0.012237,-0.021405
sub_grade_B5,-0.041985,-0.029028,-0.018689,-0.046113,-0.034070,-0.070311,0.017698,0.047660,-0.046120,-0.037881,...,-0.011778,-0.051946,-0.011778,0.020258,-0.011778,0.087078,0.024222,-0.023620,-0.011778,-0.039532
sub_grade_C1,-0.031244,-0.030838,-0.036666,0.003568,-0.047810,-0.063602,0.026956,-0.019604,-0.027804,-0.036625,...,-0.011147,-0.018890,-0.011147,0.026726,-0.011147,0.003829,-0.031725,-0.022353,-0.011147,-0.007589
sub_grade_C2,-0.024625,-0.014382,-0.037947,0.028609,0.022493,-0.027721,-0.071187,0.053773,-0.034776,-0.049145,...,-0.008869,0.042570,-0.008869,0.007145,-0.008869,0.022882,-0.025242,-0.017785,-0.008869,0.042922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
addr_state_KY,-0.033298,-0.031469,-0.028545,-0.052931,-0.029888,-0.056530,-0.068670,0.000482,-0.038491,-0.036039,...,-0.003076,-0.020437,-0.003076,-0.013996,-0.003076,-0.011646,-0.008756,-0.006169,-0.003076,-0.045922
addr_state_LA,-0.029486,-0.025658,-0.026920,-0.103862,-0.036465,-0.026735,0.000226,0.000684,-0.006201,-0.008059,...,-0.004362,-0.028980,-0.004362,-0.019847,-0.004362,-0.016514,-0.012416,-0.008748,-0.004362,-0.026793
addr_state_MA,0.001036,0.008730,0.012366,0.006007,0.028624,-0.009688,-0.032538,-0.009129,0.003716,0.007532,...,-0.005652,-0.037547,-0.005652,-0.025714,-0.005652,-0.021396,-0.016087,-0.011334,-0.005652,0.005009
addr_state_MD,0.025611,0.020644,0.016983,-0.033337,0.022624,0.062731,-0.049933,-0.037488,0.025521,0.022404,...,-0.007416,-0.049267,-0.007416,-0.033740,-0.007416,-0.028075,-0.021108,-0.014872,-0.007416,0.073261
addr_state_MI,0.023027,0.031855,0.037064,-0.051490,0.033614,-0.012573,0.071628,0.148502,0.032199,0.037497,...,-0.005357,-0.035589,-0.005357,-0.024373,-0.005357,-0.020280,-0.015248,-0.010743,-0.005357,0.014161
addr_state_MN,-0.022172,-0.027570,-0.023740,-0.005239,-0.032323,-0.051724,-0.075194,-0.027576,-0.025733,-0.022259,...,-0.003979,-0.026431,-0.003979,-0.018101,-0.003979,-0.015062,-0.011324,-0.007979,-0.003979,-0.017446
addr_state_MO,0.031888,0.030590,0.034569,0.071335,0.026581,-0.004944,0.066408,-0.011199,0.013901,0.015881,...,-0.004716,-0.031330,-0.004716,-0.021456,-0.004716,-0.017853,-0.013423,-0.009458,-0.004716,0.036142
addr_state_MT,-0.003972,-0.001858,0.000215,0.002694,-0.018023,-0.038681,-0.011582,0.000278,0.017897,0.020267,...,-0.001773,-0.011778,-0.001773,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,-0.001773,-0.026466
addr_state_NC,0.073238,0.080007,0.054490,0.071893,0.028975,0.000252,0.066499,-0.016602,-0.001129,-0.022647,...,-0.006462,-0.042927,-0.006462,-0.029398,-0.006462,-0.024462,-0.018392,-0.012958,-0.006462,0.034548
addr_state_NH,0.050681,0.056602,0.059771,0.021901,0.033392,-0.013645,0.004663,0.000278,0.090853,0.094613,...,-0.001773,-0.011778,-0.001773,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,-0.001773,-0.026466
addr_state_NJ,0.012128,0.001975,0.000523,-0.067381,0.018558,0.019499,-0.042243,-0.048045,0.040967,0.038094,...,-0.009433,-0.062664,-0.009433,-0.042915,-0.009433,-0.035709,-0.026848,-0.018916,-0.009433,-0.030313
addr_state_NM,0.035813,0.041692,0.041574,0.055820,0.035041,0.004042,0.034760,-0.021841,0.090809,0.087131,...,-0.002510,-0.016672,-0.002510,-0.011418,-0.002510,-0.009501,-0.007143,-0.005033,-0.002510,-0.037462
addr_state_NV,-0.052723,-0.050514,-0.046507,-0.023152,-0.042618,-0.012983,-0.076312,-0.025082,-0.040745,-0.036938,...,-0.004362,-0.028980,-0.004362,-0.019847,-0.004362,-0.016514,-0.012416,-0.008748,-0.004362,-0.026793
addr_state_NY,0.040610,0.019766,0.016042,0.027302,0.018616,0.062903,-0.135633,-0.011602,0.031110,0.031837,...,-0.013406,-0.089057,-0.013406,-0.060990,-0.013406,-0.050749,-0.038156,-0.026884,-0.013406,0.058086
addr_state_OH,0.009620,0.012692,0.019337,-0.040612,-0.012040,-0.023763,0.045055,-0.045218,0.010541,0.015293,...,-0.007416,-0.049267,-0.007416,-0.033740,-0.007416,-0.028075,-0.021108,-0.014872,-0.007416,0.004274
addr_state_OK,-0.059296,-0.061036,-0.060371,0.063553,-0.060281,-0.015921,0.018145,0.000278,-0.053298,-0.052628,...,-0.001773,-0.011778,-0.001773,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,-0.001773,0.066993
addr_state_OR,-0.061461,-0.058121,-0.052803,-0.107542,-0.050567,-0.086289,0.027422,-0.029159,-0.061783,-0.057089,...,-0.005652,-0.037547,-0.005652,-0.025714,-0.005652,-0.021396,-0.016087,-0.011334,-0.005652,-0.084370
addr_state_PA,-0.023042,-0.013219,-0.026307,-0.019831,-0.027813,-0.007545,0.057072,-0.012324,-0.012653,-0.021486,...,-0.008476,-0.056304,-0.008476,-0.038559,-0.008476,-0.032085,-0.024123,-0.016997,-0.008476,0.096863
addr_state_RI,-0.020217,-0.016831,-0.013235,-0.041446,-0.005569,-0.006254,0.011790,-0.046693,-0.022732,-0.019662,...,-0.003556,-0.023620,-0.003556,-0.016176,-0.003556,-0.013460,-0.010120,-0.007130,-0.003556,-0.006220
addr_state_SC,-0.043636,-0.043292,-0.041326,-0.050027,-0.039810,-0.024143,0.006647,0.000394,-0.050761,-0.049223,...,-0.002510,-0.016672,-0.002510,-0.011418,-0.002510,-0.009501,-0.007143,-0.005033,-0.002510,-0.037462
addr_state_SD,-0.021697,-0.020818,-0.019196,-0.027952,-0.015965,0.011391,-0.037034,-0.031139,-0.012916,-0.011281,...,1.000000,-0.011778,-0.001773,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,-0.001773,-0.026466
addr_state_TX,0.093604,0.084007,0.089012,0.039276,0.071730,0.010673,0.022205,-0.028695,0.083680,0.087066,...,-0.011778,1.000000,-0.011778,-0.053585,-0.011778,-0.044588,-0.033523,-0.023620,-0.011778,0.036182
addr_state_UT,-0.037811,-0.038054,-0.036843,-0.016514,-0.035066,0.022771,0.025774,-0.031139,-0.029241,-0.027996,...,-0.001773,-0.011778,1.000000,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,-0.001773,-0.026466
addr_state_VA,-0.000048,-0.014301,-0.018263,0.078576,-0.030311,-0.025891,0.007929,0.101314,0.016867,0.007817,...,-0.008066,-0.053585,-0.008066,1.000000,-0.008066,-0.030535,-0.022958,-0.016176,-0.008066,0.049668
addr_state_VT,-0.016326,-0.015072,-0.013314,-0.035937,-0.010098,-0.038681,-0.021578,0.000278,-0.008897,-0.007167,...,-0.001773,-0.011778,-0.001773,-0.008066,1.000000,-0.006712,-0.005046,-0.003556,-0.001773,-0.026466
addr_state_WA,-0.011296,-0.003033,0.004710,0.064029,-0.005801,-0.072332,0.005470,-0.049917,0.001228,0.008419,...,-0.006712,-0.044588,-0.006712,-0.030535,-0.006712,1.000000,-0.019103,-0.013460,-0.006712,-0.074918
addr_state_WI,-0.007626,-0.001353,0.004587,0.046133,0.008258,-0.018495,0.054802,0.090208,-0.004268,0.001139,...,-0.005046,-0.033523,-0.005046,-0.022958,-0.005046,-0.019103,1.000000,-0.010120,-0.005046,-0.042077
addr_state_WV,-0.019275,-0.015823,-0.011955,-0.035171,0.002047,-0.013614,0.020561,0.095059,-0.022740,-0.019388,...,-0.003556,-0.023620,-0.003556,-0.016176,-0.003556,-0.013460,-0.010120,1.000000,-0.003556,-0.006220
addr_state_WY,0.064243,0.071109,0.074771,0.062474,0.055793,0.012529,0.033600,0.031695,0.122908,0.127594,...,-0.001773,-0.011778,-0.001773,-0.008066,-0.001773,-0.006712,-0.005046,-0.003556,1.000000,-0.026466
debt_settlement_flag_Y,0.219288,0.221004,0.167402,0.229406,0.144573,0.161117,0.014596,0.174147,0.087301,0.043544,...,-0.026466,0.036182,-0.026466,0.049668,-0.026466,-0.074918,-0.042077,-0.006220,-0.026466,1.000000

In [74]:
corr_postive = corr['debt_settlement_flag_Y'].sort_values(ascending=False)
corr_postive.head()

NameError: name 'corr' is not defined

In [ ]:
corr_negative = corr['debt_settlement_flag_Y'].sort_values(ascending=True)
corr_negative.head()

In [ ]:
dummies_loans.kurtosis()

In [ ]:
dummies_loans.skew()

In [ ]:
sns.distplot(dummies_loans['total_rec_int'], hist=True, kde=False, 
             bins=int(180/5), color = 'blue',
             hist_kws={'edgecolor':'black'})
# Add labels
plt.title('total_rec_int')
plt.xlabel('total_rec_int')
plt.ylabel('debt_settlement_flag_Y')

In [ ]:
#q4(2)

In [ ]:
def sigmoid(x):1/(1+exp(-x))
def myLogisticGD(x, y, beta,alpha,
                 numIterations):
    x_add_one=np.column_stack((x,np.ones(len(x))))
    xTrans = x_add_one.transpose()
    for i in range(0, numIterations):
        model_0 = np.dot(x_add_one, beta)
        loss_temp = model_0 - y
        loss = -1/len(x)*np.sum((y*np.log(model_0)+(1-y)*np.log(1-model_0)))
        loss_total[i]= loss
        gradient = np.dot(xTrans, loss_temp) /len(x)
        beta = beta - alpha * gradient
        beta_total[i,:]=beta.transpose()
        return beta
X_loans = loans[['annual_inc','int_rate']]
y_loans = pd.get_dummies(loans['debt_settlement_flag'],drop_first=True).iloc[:,0]
numIterations = 5000
init_beta = [1,1,1]
alpha = 0.001
myLogisticGD(X_loans,y_loans,init_beta,alpha,numIterations)

In [ ]:
fig1 = plt.figure()
plt.plot(loss_total, label = "Loss fucntion")
plt.plot(beta_total[:,0], label = "Beta0")
plt.plot(beta_total[:,1], label = "Beta1")
plt.legend(loc="upper right")
plt.xlabel("Number of iteration")

In [ ]:
#q3